name: Mutation Tests

on:
  workflow_run:
    workflows: [Unit Tests]
    types: [completed]

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    strategy:
      fail-fast: true
      matrix:
        php: [8.2, 8.3, 8.5]

    name: Mutation Test PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug
          tools: pest

      - name: Test code
        run: pest --mutate --parallel
