name: Unit Tests

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - "src/**.php"
      - "tests/**.php"
      - "phpunit.xml"
      - ".github/workflows/tests.yml"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [8.2, 8.3, 8.4]
        suite: ['Architecture', 'Documentation', 'Feature', 'Unit']

    name:  PHP ${{ matrix.php }} - ${{ matrix.suite }} Tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          tools: 'pestphp/pest'

      - name: Test code
        run: pest --testsuite ${{ matrix.suite }} --parallel
